### ISSUE TITLE
Ability to edit / delete the discussion after you submit it

### ISSUE THREAD

**Issue by jmrtns** [mitar/council-app#6]
With a log would be nice

**Comment by mitar** [comment]
So authors and moderators should be allowed to edit the description? Should they be allowed to edit it always, or just until the first comment? Point? Motion? Open voting?

**Comment by mitar** [comment]
I would not allow deletion. But moderators will be able to close the discussion.

**Comment by jmrtns** [comment]
This is probably something to discuss with president or possibly council. I think it can be edited until there is a motion, by the author, especially if there is a log
